<?php
/**
 * Solwin Infotech
 * Solwin Featured Product Extension
 * 
 * @category   Solwin
 * @package    Solwin_FeaturedPro
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Solwin\FeaturedPro\Helper\Data');
$enableModule = $helper->getConfigValue('featuredpro_settings/featured_products/enable');
$enableSidebar = $helper->getConfigValue('featuredpro_settings/featured_products/enable_sidebar');
if ($enableModule && $enableSidebar) {

    $block_title = $helper->getConfigValue('featuredpro_settings/featured_products/sidebar_title');

    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        $pos = $block->getPositioned();
        $position = '';
        if ($pos != null) {
            $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
                    . 'top:' . $block->getVar("{$image}:height") . 'px;"';
        }
        $cnt = 1;
        $sidebarLimit = $helper->getConfigValue('featuredpro_settings/featured_products/sidebar_limit');
        ?>
        <div style="float: left;width:100%; padding: 10px 0;" class="pad-main-bottom wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
            <div style="margin:0;">
                <div class="block block-sidebar">
                    <div class="block-title">
                        <strong><?php echo __($block_title); ?></strong>
                    </div>
                </div>
                <?php $iterator = 1; ?>
                <ol class="products list items product-items featuredproduct">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php if ($cnt <= $sidebarLimit) { ?>
                            <?php echo($iterator++ == 1) ? '<li style="margin-top:20px;" class="item product product-item">' : '</li><li style="margin-top:20px;" class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php // Product Image     ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <span style="width:240px;" class="product-image-container">
                                        <span style="padding-bottom: 137%;" class="product-image-wrapper">
                                            <?php
                                            $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                    ->init($_product, 'product_page_image_large')
                                                    ->constrainOnly(FALSE)
                                                    ->keepAspectRatio(TRUE)
                                                    ->keepFrame(FALSE)
                                                    ->resize(270, 371)
                                                    ->getUrl();
                                            ?>
                                            <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                        </span>
                                    </span>
                                </a>

                                <div class="product details product-item-details">
                                    <div style="padding: 0 2px;"><?php echo $block->getProductDetailsHtml($_product); ?></div>
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php echo $_product->getProductUrl() ?>">
                                               <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <strong><?php echo $this->getFinalPrice($_product->getFinalPrice()); ?></strong>
                                </div>
                            </div>
                            <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                            <?php $cnt++; ?>
                        <?php } ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    <?php endif; ?>

    <script>
        require(['jquery', 'cpowlcarousel'], function () {
            jQuery(document).ready(function () {
                jQuery(".featuredproduct").owlCarousel({
                    items: 1,
                    itemsDesktop: [1080, 1],
                    itemsDesktopSmall: [860, 1],
                    itemsTablet: [768, 1],
                    itemsTabletSmall: [639, 1],
                    itemsMobile: [360, 1],
                    pagination: false,
                    navigationText: ["<div class='lft-btn'>&lt;</div>", "<div class='rgt-btn'>&gt;</div>"],
                    navigation: true,
                });
            });
        });
    </script>
    <?php
}