<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
    <a href="#" class="action print white" title="<?php /* @escapeNotVerified */ echo __('Print This Page') ?>">
        <span><i class="fa fa-print" aria-hidden="true"></i> <strong><?php /* @escapeNotVerified */ echo __('Print This Page') ?></strong></span>
    </a>
        <div class="table-wrapper comparison">
            <div class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
	                <div class="row" data-mage-init='{
   "OwlCarousel":{
         "items" : 3,
         "itemsDesktop" : false,
         "itemsDesktopSmall" : false,
         "itemsTablet" : [1070,2],
         "itemsTabletSmall" : false,
	     "itemsMobile" : [768,1],
		 "pagination" : false,
        "navigation" : true,
        "navigationText" : ["<", ">"]
   }
 }
 '>
	                    <?php $_i = 0; ?>
	                    <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
	                    <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
	                    <?php foreach ($block->getItems() as $_item): ?>
	                        <div class="cell product info col-xs-12 col-sm-6 col-lg-4">
	                            <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
	                                <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
	                            </a>
	                            <h2 class="product-item-name h4 text-center">
	                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
	                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
	                                </a>
	                            </h2>
	                            <?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
	                            <div class="text-center h5"><?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?></div>
	                            <div class="product-item-actions text-center">
	                                <div class="actions-primary">
	                                    <?php if ($_item->isSaleable()): ?>
	                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
	                                            <?php echo $block->getBlockHtml('formkey')?>
	                                            <button type="submit" class="action tocart primary cta">
	                                                <span><i class="fa fa-cart-plus" aria-hidden="true"></i> <?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
	                                            </button>
	                                        </form>
	                                    <?php else: ?>
	                                        <?php if ($_item->getIsSalable()): ?>
	                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
	                                        <?php else: ?>
	                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
	                                        <?php endif; ?>
	                                    <?php endif; ?>
	                                </div>
	                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
	                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
	                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist cta" data-action="add-to-wishlist">
	                                            <span><i class="fa fa-gift" aria-hidden="true"></i> <?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
	                                        </a>
	                                    </div>
	                                <?php endif; ?>
	                            </div>
				                <?php foreach ($block->getAttributes() as $_attribute): ?>
					                <div class="attibute value">
						            <strong class="attribute label">
                                        <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?> : 
                                    </strong>
					                    <?php switch ($_attribute->getAttributeCode()) {
					                        case "price": ?>
					                            <?php
					                                /* @escapeNotVerified */ echo $block->getProductPrice(
					                                    $_item,
					                                    '-compare-list-' . $_attribute->getCode()
					                                )
					                            ?>
					                            <?php break;
					                        case "small_image": ?>
					                            <?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
					                            <?php break;
					                        default: ?>
					                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
					                        <?php break;
					                    } ?>
					                </div>
				                <?php endforeach; ?>
		                        <div class="cell remove product text-center">
		                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
		                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataRemove($_item); ?>'
		                               class="action delete" title="<?php /* @escapeNotVerified */ echo __('Remove') ?>">
		                                <span><i class="fa fa-trash" aria-hidden="true"></i> <?php /* @escapeNotVerified */ echo __('Remove Product') ?></span>
		                            </a>
		                        </div>
	                        </div>
	                    <?php endforeach; ?>
	                </div>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
        <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?></div></div>
<?php endif; ?>
