<?php
	// for sell
	
	// src: http://magento.stackexchange.com/questions/110003/getting-sub-category-images-in-magento2/110013
	
$categories = $this->getStoreCategories(true,false,true);
$categoryHelper = $this->getCategoryHelper();
?>

	<?php // Level 0
	foreach($categories as $category):
	     if ($category->getId() != 94) {
	        continue;
	     }
	
	?>
		<?php  
		if($childrenCategories = $this->getChildCategories($category)): // Level 1
		?>
				<div class="row row-flex buyback-row">
						<?php
						foreach($childrenCategories as $childrenCategory):
						     if (!$childrenCategory->getIsActive()) {
						        continue;
						     }
						?>
						<div class="level1 col-lg-2 col-xs-12 text-center">
							<a href="<?php echo $categoryHelper->getCategoryUrl($childrenCategory) ?>">
							<?php
							    $catId = $childrenCategory->getId();
							    $categoryAgain = $this->getCategoryView()->load($catId);
							    $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
							    $_imgHtml   = '';
							    if ($_imgUrl = $categoryAgain->getImageUrl()) {
							        $_imgHtml = '<img src="' . $_imgUrl . '" />';
							        $_imgHtml = $_outputhelper->categoryAttribute($categoryAgain, $_imgHtml, 'image');
							        /* @escapeNotVerified */ 
							        echo $_imgHtml;
							    }
							?>
							</a>
							<h2><a href="<?php echo $categoryHelper->getCategoryUrl($childrenCategory) ?>"><?php echo $childrenCategory->getName() ?></a></h2>
						</div>
					<?php
					endforeach; // Level 1 foreach
					?>
				</div>
		<?php endif; // Level 1 if ?>
<?php
endforeach; // Level 0 foreach
?>
