<ul class="header-right-links">
	<li><a href="tel:9547072079"><strong>(954) 707-2079</strong></a></li>
</ul>

<!--a href="<?php echo $block->getUrl(''); ?>wholesale"><strong>Wholesale</strong></a-->

<div class="sign-in-wrapper">
	<div class="sign-in-vector">
		<svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M0,-2.6551451e-15 L100,-2.6551451e-15 L100,83.2162338 C100,83.2162338 84.2957823,100 50,100 C15.7042177,100 0,83.2030146 0,83.2030146 L0,-2.6551451e-15 Z" stroke="none" fill="#1f3a66" fill-rule="evenodd"/></svg>
	</div>
	<ul class="header links" style="color: #FDB028"><li style="line-height: 2.75;"><a href="<?php echo $block->getUrl(''); ?>wholesale">Wholesale</a></li>
</ul></div>