<div class="home-vector-polygon">
<svg viewBox="0 0 100 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<polygon points="0,0 100,0 0,100" fill="#1F3A66" />
</svg>
	<div class="shop-button">
		<a href="<?php echo $this->getUrl("home") ?>#">Start Shopping <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
	</div>
</div>