<h2 class="white">Frequently Asked Questions</h2>
<div id="wholesale-accordions" class="row row-flex" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
	<div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet lorem at velit varius vulputate nec a lorem. Praesent rhoncus placerat consequat. Duis condimentum mauris a urna ultrices euismod sit amet in diam. Quisque accumsan leo ut sapien pretium pretium. Duis rutrum consequat justo, a vestibulum magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc nec posuere mauris. Quisque imperdiet nisl et efficitur tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque sit amet commodo enim. Aliquam et ligula vulputate, pharetra elit eu, rutrum diam. Cras placerat eget elit posuere molestie. Mauris mollis iaculis augue.</div>
	</div>

	<div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Donec hendrerit felis vel tempus cursus?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Pellentesque interdum ex eget nulla auctor iaculis. Vestibulum nec enim non justo mattis aliquam. Nam vitae lacus nec ligula faucibus sodales. Aliquam erat volutpat. Vivamus pulvinar diam pretium vulputate imperdiet. Duis scelerisque sollicitudin mattis. In vitae felis elit. Cras in bibendum odio. Curabitur imperdiet vel erat eu faucibus. Quisque ut enim vitae sapien interdum consectetur eget eget dui. Nulla luctus nulla a nunc condimentum, nec hendrerit nisl aliquet. Etiam rutrum orci vitae risus tempus porttitor. Nulla consequat placerat risus, sed facilisis nunc lobortis vel. Phasellus ipsum arcu, lacinia vel finibus at, luctus dignissim mi. Pellentesque at bibendum orci. Curabitur eget diam pharetra, molestie ipsum vel, bibendum lacus.</div>
	</div>

	<div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Nunc molestie arcu non lacus vulputate, in auctor eros auctor?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Nam dignissim diam elit, luctus accumsan diam ornare eu. Donec efficitur arcu sed ipsum laoreet ultrices. Curabitur tristique pretium leo, ut rutrum dui mattis eget. Cras metus odio, facilisis vitae aliquam ut, convallis id turpis. Duis sit amet feugiat massa. Suspendisse tincidunt lorem a volutpat varius. Fusce auctor euismod ante sed porttitor. Nam a felis eu turpis venenatis mattis vel hendrerit justo. Nam rhoncus viverra sem, at consequat ex convallis vitae. Integer nibh enim, venenatis vitae neque id, aliquam posuere magna. Etiam varius congue accumsan. Curabitur non venenatis magna, sit amet iaculis mauris. Nulla efficitur nulla quis sagittis iaculis. Quisque laoreet, lorem sit amet pulvinar tincidunt, dui tellus congue augue, a ultrices purus velit ac lectus. Suspendisse scelerisque vehicula metus, eget congue nisi.</div>
	</div>
	
    <div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Mauris sit amet lacus tristique, laoreet erat non, gravida est?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Pellentesque quis feugiat nisi, eget pellentesque justo. Sed id tristique nisl. Mauris massa ante, venenatis vel ex placerat, feugiat iaculis neque. Phasellus dui magna, commodo id accumsan eu, dapibus posuere ex. Nam ac ipsum sit amet est cursus gravida. Aliquam id pretium justo. Vivamus eget lacus sit amet tellus auctor sodales nec eget velit. Nullam ex nisl, tincidunt sit amet mauris eu, euismod ultrices mi. Vestibulum sodales congue lorem, eget eleifend sem bibendum ut. Proin in nisi volutpat, consequat est sit amet, laoreet metus. Praesent posuere sed orci sit amet suscipit. Mauris sodales quam sed finibus porttitor. Phasellus porta lorem ut felis consequat, luctus eleifend quam viverra. Duis tincidunt pharetra iaculis. Nulla sit amet massa mi. Quisque scelerisque tincidunt lacinia.</div>
    </div>
    
    <div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Nunc consequat nunc vulputate, ultrices magna eget, suscipit justo?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Nullam neque nisl, tincidunt at justo sit amet, commodo accumsan risus. Nulla elit tellus, venenatis sit amet magna ac, ultricies luctus mauris. Nulla nec sapien in lorem pulvinar hendrerit. Donec vel est non tellus ultrices tincidunt sit amet vitae dolor. Quisque tempus enim non quam convallis faucibus. In tincidunt magna bibendum metus pharetra sodales at a tellus. Vestibulum dignissim ullamcorper felis at facilisis. Mauris lobortis lorem ligula, in lobortis lectus commodo sit amet. Aenean et interdum odio, vel lobortis metus.</div>
    </div>
    
    <div class="col-xs-12 col-lg-6">
    <div data-role="collapsible" class="accordion h6">
        <div data-role="trigger">
            <span>Donec eleifend dui quis tortor tincidunt, sed suscipit libero cursus?</span>
        </div>
    </div>
    <div data-role="content" class="accordion-content">Aenean id sapien faucibus, feugiat purus at, interdum diam. Curabitur in elit ac turpis tempor facilisis. Aenean ligula felis, ullamcorper ac mi a, lobortis consequat nibh. Etiam magna lorem, posuere vel libero vitae, maximus volutpat tortor. Nunc non ultrices ligula. Proin eu tellus ullamcorper, scelerisque nulla sed, tempus magna. Quisque vitae rutrum eros. Integer non dolor in magna fringilla dignissim vel sit amet enim. Cras malesuada, velit venenatis porttitor ultricies, erat felis finibus urna, non porttitor ipsum enim sed ex. Proin volutpat purus in turpis faucibus, a dignissim lectus tempus. Suspendisse placerat neque nec imperdiet efficitur. Morbi sit amet orci gravida, venenatis diam pellentesque, varius urna. Nam porttitor orci non sapien elementum, nec viverra libero varius. Curabitur auctor est in odio fringilla, sit amet pharetra felis pretium. Phasellus vestibulum condimentum lacus lacinia volutpat.</div>
    </div>
</div>
<div class="col-xs-12"><a href="#apply" class="cta">Click Here to Apply</a></div>