<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <strong>Availability:</strong> <span><em><?php /* @escapeNotVerified */ echo __('In Stock') ?></em></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <strong>Availability:</strong> <span><em><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></em></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
