<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<a href="#" data-role="remove" data-post-remove='<?php /* @escapeNotVerified */ echo $block->getItemRemoveParams($block->getItem()); ?>' title="<?php /* @escapeNotVerified */ echo __('Remove Item') ?>" class="btn-remove action delete col-xs-12 col-sm-6 text-center">
    <span><i class="fa fa-times" aria-hidden="true"></i> <?php /* @escapeNotVerified */ echo __('Remove item');?></span>
</a>
