<!--
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<ul class="opc-progress-bar text-center white">
	<div class="progress-bar-under">
		<div class="col-xs-6 progress-bar-under-block _active"></div>
		<div class="col-xs-6 progress-bar-under-block"></div>
	</div>
	<div class="container">
		<div class="row row-flex">
	        <li class="opc-progress-bar-item col-xs-4 _active">
	            <span>Cart</span>
	            <div class="opc-progress-bar-icon"></div>
	        </li>			
	        <li class="opc-progress-bar-item col-xs-4">
	            <span>Shipping</span>
	            <div class="opc-progress-bar-icon"></div>
	        </li>
	        <li class="opc-progress-bar-item col-xs-4">
	            <span>Review &amp; Payments</span>
	            <div class="opc-progress-bar-icon"></div>
	        </li>
		</div>
	</div>
</ul>
