<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav account-activity">
	<div class="emblem">
		<img src='<?php echo $this->getViewFileUrl('images/Seller.svg'); ?>' class="activity-icon" />
	</div>
    <h2 class="title text-center">
        <strong><?php /* @escapeNotVerified */ echo __('Account Activity'); ?></strong>
    </h2>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
