<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <thead class="h4">
                <tr class="row">
	                <th class="col items col-sm-4" scope="col"><span><?php /* @escapeNotVerified */ echo __('Item') ?></span></th>
                    <th class="col subtotal col-sm-4 pull-right" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
    </div>
    <div class="cart main actions row text-center">
        <?php if ($block->getContinueShoppingUrl()): ?>
        <div class="col-xs-12 col-sm-4">
            <a class="action continue"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <i class="fa fa-chevron-left" aria-hidden="true"></i> <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        </div>
        <?php endif; ?>
        <div class="col-xs-12 col-sm-4">
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <i class="fa fa-trash" aria-hidden="true"></i> <span><?php /* @escapeNotVerified */ echo __('Clear Cart'); ?></span>
        </button>
        </div>
        <div class="col-xs-12 col-sm-4">
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Cart')); ?>"
                class="action update">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> <span><?php /* @escapeNotVerified */ echo __('Update Cart'); ?></span>
        </button>
        </div>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

