<div class="container text-center social-icons">
	<h3 class="font-light h1">Get In Touch!</h3>
	<ul>
		<li class="white"><a href="mailto:info@bukuwireless.com"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
		<li class="white"><a href="tel:8444213563"><i class="fa fa-phone" aria-hidden="true"></i></a></li>
		<li class="white"><a href="https://www.facebook.com/Buku-Wireless-1741905226041503/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
		<li class="white"><a href="https://twitter.com/BukuWireless"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
		<li class="white"><a href="https://www.instagram.com/bukuwireless/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
		<li class="white"><a href="https://plus.google.com/109605546836516261431"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
	</ul>
</div>