<?php $home = $block->getUrl(''); ?>

<div class="footer-menu white">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-4 footer-menu-list">
				<h3 class="h1">Customer Service</h3>
				<ul>
					<li><a href="<?php echo $home; ?>contact">Contact Us</a></li>
					<li><a href="<?php echo $home; ?>returns">Returns</a></li>
					<li><a href="<?php echo $home; ?>sitemap">Sitemap</a></li>
				</ul>
			</div>
			<div class="col-xs-12 col-sm-4 footer-menu-list">
				<h3 class="h1">Information</h3>
				<ul>
					<li><a href="<?php echo $home; ?>about">About Us</a></li>
					<li><a href="<?php echo $home; ?>wholesale">Wholesale</a></li>
					<li><a href="<?php echo $home; ?>return-policy">Return Policy</a></li>
					<li><a href="<?php echo $home; ?>privacy-policy">Privacy Policy</a></li>
					<li><a href="<?php echo $home; ?>terms-conditions">Terms &amp; Conditions</a></li>
				</ul>
			</div>
			<div class="col-xs-12 col-sm-4 footer-menu-list">
				<h3 class="h1">My Account</h3>
				<ul>
					<li><a href="<?php echo $home; ?>customer/account/">My Account</a></li>
					<li><a href="<?php echo $home; ?>orders">Order History</a></li>
					<li><a href="<?php echo $home; ?>wishlist">Wishlist</a></li>
					<li><a href="<?php echo $home; ?>newsletter/manage">Newsletter</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>