<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions-toolbar">
    <div class="secondary"><a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><i aria-hidden="true" class="fa fa-chevron-left"></i> <span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a></div>
</div>
